### ISSUE TITLE
Proposal for a new project name

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/panel-example#3]
I propose to change the project name to `panel-pyvista` to match the naming convention of the [awesome-panel](https://github.com/awesome-panel) repositories.

**Comment by akaszynski** [comment]
Sounds good. Your thoughts @banesullivan?

**Comment by banesullivan** [comment]
Let's hold off for now so that we can reserve the name `panel-pyvista` for a potential extension package that wraps the components necessary for using PyVista with Panel in a seamless manner. For now, this is more of a demo/example than a re-useable package

**Comment by banesullivan** [comment]
That said, this repository could be renamed to `panel-pyvista` and it could naturally evolve into that package.... in hindsight, I'm +1 for this

**Comment by tkoyama010** [comment]
Thank you for your opinion. This is not a pressing proposal, so please do it when it is convenient for you. I am excited to see how this project will evolve!

**Comment by akaszynski** [comment]
Renamed to `panel-pyvista`. Thanks all!
